[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false

[runner]
fastReruns = true

[theme]
base = "light"

[ui]
hideTopBar = true

[global]
showSidebarNavigation = false
disableWatchdogWarning = true

[logger]
level = "error"